<?php

namespace ContainerANZZdLd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MFPVaGPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MFPVaGP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MFPVaGP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'product' => ['privates', '.errored..service_locator.MFPVaGP.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.MFPVaGP": it needs an instance of "App\\Entity\\Product" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'product' => 'App\\Entity\\Product',
            'entityManager' => '?',
        ]);
    }
}
