<?php

namespace ContainerANZZdLd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebugBundlesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DebugBundlesCommand' shared autowired service.
     *
     * @return \App\Command\DebugBundlesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DebugBundlesCommand.php';

        $container->privates['App\\Command\\DebugBundlesCommand'] = $instance = new \App\Command\DebugBundlesCommand(($container->services['kernel'] ?? $container->get('kernel', 1)));

        $instance->setName('app:debug:bundles');

        return $instance;
    }
}
