<?php

namespace ContainerANZZdLd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleControllerconnectActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wLvy5Az.App\Controller\GoogleController::connectAction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wLvy5Az.App\\Controller\\GoogleController::connectAction()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientRegistry' => ['services', 'knpu.oauth2.registry', 'getKnpu_Oauth2_RegistryService', true],
        ], [
            'clientRegistry' => '?',
        ]))->withContext('App\\Controller\\GoogleController::connectAction()', $container);
    }
}
