<?php

namespace ContainerANZZdLd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControlleraddReviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MFPVaGP.App\Controller\ReviewController::addReview()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MFPVaGP.App\\Controller\\ReviewController::addReview()'] = ($container->privates['.service_locator.MFPVaGP'] ?? $container->load('get_ServiceLocator_MFPVaGPService'))->withContext('App\\Controller\\ReviewController::addReview()', $container);
    }
}
