<?php

namespace ContainerPEOgTmB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordDebugControllertestAuthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.03VYXLr.App\Controller\PasswordDebugController::testAuth()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.03VYXLr.App\\Controller\\PasswordDebugController::testAuth()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'authenticator' => ['privates', 'App\\Security\\FormLoginAuthenticator', 'getFormLoginAuthenticatorService', true],
            'csrfTokenManager' => ['privates', 'security.csrf.same_origin_token_manager', 'getSecurity_Csrf_SameOriginTokenManagerService', false],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'authenticator' => 'App\\Security\\FormLoginAuthenticator',
            'csrfTokenManager' => '?',
        ]))->withContext('App\\Controller\\PasswordDebugController::testAuth()', $container);
    }
}
