<?php

namespace ContainerPEOgTmB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iXj7DpL.App\Controller\ProductController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iXj7DpL.App\\Controller\\ProductController::index()'] = ($container->privates['.service_locator.iXj7DpL'] ?? $container->load('get_ServiceLocator_IXj7DpLService'))->withContext('App\\Controller\\ProductController::index()', $container);
    }
}
