<?php

namespace ContainerYOeYmSe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4cMiwZxService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.4cMiwZx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4cMiwZx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderRepository' => ['privates', '.errored.e9yKrBY', NULL, 'Cannot determine controller argument for "App\\Controller\\Admin\\AdminController::orders()": the $orderRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\OrderRepository".'],
        ], [
            'orderRepository' => '?',
        ]);
    }
}
