<?php

namespace ContainerYOeYmSe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_E9yKrBYService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.errored.e9yKrBY' shared service.
     *
     * @return \App\Repository\OrderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Admin\\AdminController::orders()": the $orderRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\OrderRepository".');
    }
}
