<?php

namespace ContainerYOeYmSe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSampleProductsCommand_LazyService extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateSampleProductsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\CreateSampleProductsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-sample-products', [], 'Create sample products for testing', false, #[\Closure(name: 'App\\Command\\CreateSampleProductsCommand')] fn (): \App\Command\CreateSampleProductsCommand => ($container->privates['App\\Command\\CreateSampleProductsCommand'] ?? $container->load('getCreateSampleProductsCommandService')));
    }
}
