<?php

namespace ContainerYOeYmSe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrder2Service extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LEf9U9t.App\Entity\Order' shared service.
     *
     * @return \App\Entity\Order
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LEf9U9t": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".');
    }
}
