<?php

namespace ContainerJKnxfuM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerdeleteCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gADJ5td.App\Controller\Admin\AdminController::deleteCategory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gADJ5td.App\\Controller\\Admin\\AdminController::deleteCategory()'] = ($container->privates['.service_locator.gADJ5td'] ?? $container->load('get_ServiceLocator_GADJ5tdService'))->withContext('App\\Controller\\Admin\\AdminController::deleteCategory()', $container);
    }
}
