<?php

namespace ContainerJKnxfuM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSampleProductsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateSampleProductsCommand' shared autowired service.
     *
     * @return \App\Command\CreateSampleProductsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CreateSampleProductsCommand.php';

        $container->privates['App\\Command\\CreateSampleProductsCommand'] = $instance = new \App\Command\CreateSampleProductsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:create-sample-products');
        $instance->setDescription('Create sample products for testing');

        return $instance;
    }
}
