<?php

namespace ContainerJKnxfuM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U.6BHlN.App\Controller\CheckoutController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U.6BHlN.App\\Controller\\CheckoutController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartService' => ['privates', 'App\\Service\\CartService', 'getCartServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'cartService' => 'App\\Service\\CartService',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\CheckoutController::index()', $container);
    }
}
