<?php

namespace ContainerJKnxfuM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouponServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CouponService' shared autowired service.
     *
     * @return \App\Service\CouponService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CouponService.php';

        return $container->privates['App\\Service\\CouponService'] = new \App\Service\CouponService(($container->privates['App\\Repository\\CouponRepository'] ?? $container->load('getCouponRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
