<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYOeYmSe\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYOeYmSe/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerYOeYmSe.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerYOeYmSe\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerYOeYmSe\App_KernelProdDebugContainer([
    'container.build_hash' => 'YOeYmSe',
    'container.build_id' => 'bf65c38e',
    'container.build_time' => 1748440868,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYOeYmSe');
