services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Twig Extensions
    App\Twig\CategoryExtension:
        tags: ['twig.extension']

    # Services with explicit session binding
    App\Service\CartService:
        arguments:
            $requestStack: '@request_stack'
            $productRepository: '@App\Repository\ProductRepository'
            $couponService: '@App\Service\CouponService'

    App\Service\CouponService:
        arguments:
            $couponRepository: '@App\Repository\CouponRepository'
            $entityManager: '@doctrine.orm.entity_manager'
            $requestStack: '@request_stack'
