<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerANZZdLd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerANZZdLd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerANZZdLd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerANZZdLd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerANZZdLd\App_KernelDevDebugContainer([
    'container.build_hash' => 'ANZZdLd',
    'container.build_id' => '5ab5e122',
    'container.build_time' => 1748440885,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerANZZdLd');
