<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPEOgTmB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPEOgTmB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPEOgTmB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPEOgTmB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPEOgTmB\App_KernelDevDebugContainer([
    'container.build_hash' => 'PEOgTmB',
    'container.build_id' => '5e5d071b',
    'container.build_time' => 1748514708,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPEOgTmB');
