<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderItem extends \App\Entity\OrderItem implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'orderRef' => [parent::class, 'orderRef', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'product' => [parent::class, 'product', null, 16],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null, 16],
        "\0".parent::class."\0".'total' => [parent::class, 'total', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'orderRef' => [parent::class, 'orderRef', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'product' => [parent::class, 'product', null, 16],
        'quantity' => [parent::class, 'quantity', null, 16],
        'total' => [parent::class, 'total', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
